name: Forex News Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  forex:
    runs-on: ubuntu-latest

    steps:
      - name: Get Forex News
        run: |
          NEWS=$(curl -s https://www.forexlive.com/feed/ | head -c 1500)

          curl -H "Title: Forex Update" \
          -d "$NEWS" \
          https://ntfy.sh/forex_pai_2026
